name: Deployment

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build react app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
        yarn install --frozen-lockfile
        yarn build
    - name: Upload builded files
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build/

  deploy:
    name: Deploy react app
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_KEY }}
          public-key: ${{ secrets.SSH_KEY_PUBLIC }}
          name: id_rsa
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Download builded files
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Run deploy script
        run: |
          ls build/
          bash build/deploy.sh
