name: Deployment

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn install, build
      run: |
        yarn install --frozen-lockfile
        yarn build
    - name: Upload builded files
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build/
    - name: Upload ssh_config.sh
      uses: actions/upload-artifact@v1
      with:
        name: scripts
        path: ssh_config.sh
    - name: Upload deploy.sh
      uses: actions/upload-artifact@v1
      with:
        name: scripts
        path: deploy.sh

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download builded files
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Download scripts
      uses: actions/download-artifact@v1
      with:
        name: scripts
    # - name: ls -a via OPEN SSH Private Key
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.KNOWN_HOSTS }}
    #     username: TaKO8Ki
    #     key: ${{ secrets.SSH_KEY }}
    #     script: ls
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@master
      env:
        DEPLOY_KEY: ${{secrets.SSH_KEY}}
      with:
        flags: '-avzr --delete'
        options: '' 
        src: 'build/'
        dst: 'TaKO8Ki@133.130.122.93:/services/react-portfolio/'
